-- Content requests reuse login_token on every protected resource. The existing
-- production table has no index, so use a non-unique index without assuming
-- historical token uniqueness.
CREATE INDEX idx_login_token_token ON login_token (token);

CREATE TABLE web_project
(
    id                 BIGINT       NOT NULL PRIMARY KEY COMMENT 'project id generated by the service',
    owner_user_id      BIGINT       NOT NULL COMMENT 'creator and sole manager',
    name               VARCHAR(256) NOT NULL COMMENT 'display name, at most 256 Unicode characters',
    description        TEXT         NOT NULL COMMENT 'plain text description',
    slug               VARCHAR(256) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'public URL segment',
    access_mode        TINYINT UNSIGNED NOT NULL COMMENT '1 owner, 2 members, 3 authenticated, 4 public',
    status             TINYINT UNSIGNED NOT NULL COMMENT '1 draft, 2 enabled, 3 disabled, 4 deleted',
    current_release_id BIGINT       NULL COMMENT 'currently published release',
    revision           BIGINT       NOT NULL DEFAULT 1 COMMENT 'optimistic lock revision',
    client_request_id  VARCHAR(256) NULL COMMENT 'optional create idempotency key',
    deleted_at         DATETIME(6)  NULL COMMENT 'start of delete retention period',
    create_time        DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    update_time        DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    UNIQUE KEY uk_web_project_slug (slug),
    UNIQUE KEY uk_web_project_owner_request (owner_user_id, client_request_id),
    KEY idx_web_project_owner_id (owner_user_id, id),
    KEY idx_web_project_status_deleted_id (status, deleted_at, id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT 'hosted static web projects';

CREATE TABLE web_project_member
(
    project_id BIGINT      NOT NULL,
    user_id    BIGINT      NOT NULL,
    created_by BIGINT      NOT NULL,
    create_time DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (project_id, user_id),
    KEY idx_web_project_member_user_project (user_id, project_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT 'web project read members';

CREATE TABLE web_project_release
(
    id              BIGINT        NOT NULL PRIMARY KEY COMMENT 'release id generated by the service',
    project_id      BIGINT        NOT NULL,
    uploaded_by     BIGINT        NOT NULL,
    storage_key     VARCHAR(512)  NOT NULL COMMENT 'service generated path relative to storage root',
    status          TINYINT UNSIGNED NOT NULL COMMENT '1 uploading, 2 ready, 3 failed, 4 deleting',
    entry_file      VARCHAR(2048) NOT NULL COMMENT 'validated HTML path relative to release content root',
    sha256          CHAR(64)      NOT NULL,
    file_count      INT           NOT NULL,
    total_bytes     BIGINT        NOT NULL,
    idempotency_key VARCHAR(256)  NULL COMMENT 'optional upload idempotency key',
    extra           TEXT         NOT NULL COMMENT 'JSON object for extensible release metadata, including error_message',
    create_time     DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    update_time     DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    UNIQUE KEY uk_web_project_release_storage (storage_key),
    UNIQUE KEY uk_web_project_release_idempotency (project_id, idempotency_key),
    KEY idx_web_project_release_project_id (project_id, id),
    KEY idx_web_project_release_status_update_id (status, update_time, id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT 'immutable static web project releases';
