CREATE TABLE files
(
    id            BIGINT       NOT NULL PRIMARY KEY COMMENT 'file id generated by the service',
    owner_user_id BIGINT       NOT NULL COMMENT 'uploader and sole manager',
    original_name VARCHAR(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'display-only upload filename',
    storage_key   VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'opaque path relative to the private file root',
    size_bytes    BIGINT       NOT NULL COMMENT 'verified stored bytes',
    sha256        CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'lowercase content digest',
    deleted_at    DATETIME(6)  NULL COMMENT 'logical deletion invalidates every share',
    create_time   DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UNIQUE KEY uk_files_storage_key (storage_key),
    KEY idx_files_owner_id (owner_user_id, id),
    KEY idx_files_owner_deleted_id (owner_user_id, deleted_at, id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT 'privately stored ordinary files';

CREATE TABLE file_shares
(
    id             BIGINT       NOT NULL PRIMARY KEY COMMENT 'share id generated by the service',
    file_id        BIGINT       NOT NULL,
    owner_user_id  BIGINT       NOT NULL COMMENT 'denormalized immutable owner for bounded queries',
    token          VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '32 random bytes encoded as base64url',
    access_mode    TINYINT UNSIGNED NOT NULL COMMENT '1 public, 2 authenticated, 3 members',
    secret_mode    TINYINT UNSIGNED NOT NULL COMMENT '1 none, 2 six-character code, 3 password',
    secret_hash    VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'bcrypt hash or empty string',
    expires_at     DATETIME(6)  NULL,
    max_downloads  BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'zero means unlimited',
    download_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    revoked_at     DATETIME(6)  NULL,
    create_time    DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    update_time    DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    UNIQUE KEY uk_file_shares_token (token),
    KEY idx_file_shares_file_id (file_id, id),
    KEY idx_file_shares_owner_id (owner_user_id, id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT 'independent access policies for stored files';

CREATE TABLE file_share_members
(
    share_id   BIGINT      NOT NULL,
    user_id    BIGINT      NOT NULL,
    create_time DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (share_id, user_id),
    KEY idx_file_share_members_user_share (user_id, share_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT 'explicit readers for member file shares';
