CREATE TABLE manuals
(
    id                BIGINT       NOT NULL PRIMARY KEY COMMENT 'manual id generated by the service',
    owner_user_id     BIGINT       NOT NULL COMMENT 'creator and sole manager',
    name              VARCHAR(120) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'display name, at most 120 Unicode characters',
    description       TEXT         NOT NULL COMMENT 'plain text description',
    access_mode       TINYINT UNSIGNED NOT NULL COMMENT '1 owner, 2 authenticated, 3 public',
    status            TINYINT UNSIGNED NOT NULL COMMENT '1 draft, 2 active, 3 deleted',
    cover_item_id     BIGINT       NULL COMMENT 'explicitly selected non-deleted item, NULL selects the automatic cover',
    revision          BIGINT       NOT NULL DEFAULT 1 COMMENT 'optimistic lock revision',
    client_request_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'create idempotency key',
    request_hash      CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'canonical create input SHA-256',
    create_time       DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    update_time       DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    UNIQUE KEY uk_manuals_owner_request (owner_user_id, client_request_id),
    KEY idx_manuals_owner_status_id (owner_user_id, status, id),
    KEY idx_manuals_access_status_id (access_mode, status, id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT 'private and shared equipment manuals';

CREATE TABLE manual_categories
(
    manual_id         BIGINT       NOT NULL,
    category          VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'trimmed owner-defined category',
    create_time       DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (manual_id, category),
    KEY idx_manual_categories_category_manual (category, manual_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT 'manual to category relationships';

CREATE TABLE manual_items
(
    id                BIGINT       NOT NULL PRIMARY KEY COMMENT 'manual item id generated by the service',
    manual_id         BIGINT       NOT NULL,
    kind              TINYINT UNSIGNED NOT NULL COMMENT '1 image, 2 pdf, 3 text, 4 url',
    title             VARCHAR(200) NOT NULL,
    text              MEDIUMTEXT   NOT NULL COMMENT 'plain text item body',
    url               VARCHAR(2048) NOT NULL COMMENT 'validated http or https URL',
    storage_key       VARCHAR(512) NULL COMMENT 'service-generated original path relative to manuals root',
    thumbnail_key     VARCHAR(512) NULL COMMENT 'service-generated JPEG thumbnail path',
    content_type      VARCHAR(128) NOT NULL,
    original_name     VARCHAR(512) NOT NULL,
    size_bytes        BIGINT       NOT NULL DEFAULT 0 COMMENT 'original bytes, retained rows keep counting toward quota',
    sha256            CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    position          INT UNSIGNED NOT NULL,
    preview_status    TINYINT UNSIGNED NOT NULL COMMENT '1 none, 2 ready, 3 unavailable',
    client_request_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'append idempotency key',
    request_hash      CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'canonical item input SHA-256',
    deleted_at        DATETIME(6)  NULL COMMENT 'logical deletion, original remains allocated',
    create_time       DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UNIQUE KEY uk_manual_items_request (manual_id, client_request_id),
    UNIQUE KEY uk_manual_items_storage (storage_key),
    KEY idx_manual_items_manual_active_position (manual_id, deleted_at, position, id),
    KEY idx_manual_items_manual_id (manual_id, id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT 'ordered manual image, pdf, text and URL items';
