server:
  # http server 的服务端口
  port: 8080
rpc:
  jmisbn:
    # 云市场的接口 https://market.aliyun.com/products/57126001/cmapi00053669.html?spm=5176.730005.result.6.f32d3524quBk45&innerSource=search_isbn#sku=yuncode4766900001
    app_code: 702c7ad931a94bc397c181c38aa25792
  cloudflare:
    api_key: xxxx
    zone_id: xxxx
    account_id: xxxx
mysql:
  master_db: test:123456@tcp(127.0.0.1:3306)/home_server?charset=utf8mb4&parseTime=True&loc=Local
passport:
  mock_data: '[{"id":123,"user_name":"test","password":"$2a$04$R2Csdr0qO4JEHxawUyysM.xiv266hVHiNh.hoUCAwpNObRFMyisE6","email":"m123@123.com","mobile":"12345678901","create_time":"0001-01-01T00:00:00Z","update_time":"0001-01-01T00:00:00Z"}]'
  redirect_login_path: https://example.com/login