<template>
  <div class="page-toolbar"><div><h1 class="page-title">网页审核</h1><p class="muted">可检查所有用户的网页及保留期内版本，不受普通可见范围限制。</p></div><el-button :loading="loading" @click="load(true)">刷新</el-button></div>
  <section class="surface-card section-card">
    <el-form class="filter-row" @submit.prevent="load(true)"><el-input v-model="filters.owner_user_id" placeholder="所有者用户 ID" clearable /><el-input v-model="filters.query" placeholder="网页名 / slug" clearable /><el-select v-model="filters.status" clearable placeholder="发布状态"><el-option v-for="(label, value) in statusText" :key="value" :label="label" :value="value" /></el-select><el-select v-model="filters.access_mode" clearable placeholder="可见范围"><el-option v-for="(label, value) in accessText" :key="value" :label="label" :value="value" /></el-select><el-select v-model="filters.moderation_status" clearable placeholder="审核状态"><el-option v-for="(label, value) in moderationText" :key="value" :label="label" :value="value" /></el-select><el-button native-type="submit" :loading="loading">查询</el-button></el-form>
    <el-alert v-if="error" type="error" :title="error" :closable="false" class="form-message" />
    <el-table :data="items" v-loading="loading" row-key="id" empty-text="没有符合条件的网页"><el-table-column label="网页" min-width="190"><template #default="{row}"><el-button type="primary" link @click="viewProject(row)">{{ row.name || row.slug }}</el-button><div class="muted">/{{ row.slug }} · {{ row.id }}</div></template></el-table-column><el-table-column label="所有者" min-width="135"><template #default="{row}"><UserIdentity :user="row.owner_user || {user_id: row.owner_user_id, user_name: row.user_name || row.owner_user_name}" secondary /></template></el-table-column><el-table-column label="状态 / 可见范围" min-width="170"><template #default="{row}"><div class="tag-list"><el-tag>{{ statusText[row.status] || row.status }}</el-tag><el-tag type="info">{{ accessText[row.access_mode] || row.access_mode }}</el-tag></div><small v-if="row.moderation_status !== 'normal'" class="moderation-warning">{{ moderationText[row.moderation_status] || row.moderation_status }} · {{ row.moderation_reason || row.reason }}</small></template></el-table-column><el-table-column label="更新时间" min-width="180"><template #default="{row}">{{ dateTime(row.update_time) }}</template></el-table-column><el-table-column label="操作" min-width="170" fixed="right"><template #default="{row}"><el-button type="primary" link @click="viewProject(row)">详情</el-button><el-dropdown trigger="click" @command="action => beginAction(row, action)"><el-button type="primary" link>处置⌄</el-button><template #dropdown><el-dropdown-menu><el-dropdown-item v-if="row.status !== 'deleted' && row.moderation_status !== 'blocked'" command="block">下架并锁定</el-dropdown-item><el-dropdown-item v-if="row.status !== 'deleted'" command="delete">删除网页</el-dropdown-item><el-dropdown-item v-if="row.status === 'deleted'" command="restore">恢复为停用状态</el-dropdown-item><el-dropdown-item v-if="row.moderation_status === 'blocked' && row.status !== 'deleted'" command="unblock">解除审核锁</el-dropdown-item></el-dropdown-menu></template></el-dropdown></template></el-table-column></el-table>
    <div v-if="hasMore" class="data-footer"><el-button :loading="loading" @click="load(false)">加载更多</el-button></div>
  </section>
  <el-drawer v-model="detailVisible" :title="detail?.project?.name || '网页详情'" size="min(860px, 96vw)"><el-skeleton v-if="detailLoading" animated :rows="7" /><template v-else-if="detail"><dl class="meta-list"><dt>项目 ID</dt><dd>{{ detail.project.id }}</dd><dt>所有者</dt><dd><UserIdentity :user="detail.project.owner_user || {user_id: detail.project.owner_user_id, user_name: detail.project.user_name || detail.project.owner_user_name}" secondary /></dd><dt>发布路径</dt><dd>/{{ detail.project.slug }}</dd><dt>可见范围</dt><dd>{{ accessText[detail.project.access_mode] }} <span v-if="detail.project.member_user_ids?.length">（成员 {{ detail.project.member_user_ids.join('、') }}）</span></dd><dt>当前版本</dt><dd>{{ detail.project.current_release_id || '尚未发布' }}</dd><dt>发布 / 审核</dt><dd>{{ statusText[detail.project.status] }} / {{ moderationText[detail.project.moderation_status] || '正常' }}</dd><dt>审核原因</dt><dd>{{ detail.project.moderation_reason || detail.project.reason || '—' }}</dd><dt>保留期至</dt><dd>{{ dateTime(detail.project.purge_after) }}</dd></dl>
    <h2 class="release-heading">历史版本</h2><el-alert title="预览会执行上传的 HTML 与脚本，仍与主站同源。请先查看元信息，再决定是否打开。" type="warning" :closable="false" class="form-message" />
    <el-table :data="detail.releases || []" empty-text="暂无版本"><el-table-column type="expand"><template #default="{row}"><dl class="meta-list release-details"><dt>文件数</dt><dd>{{ row.file_count ?? '—' }}</dd><dt>总大小</dt><dd>{{ bytes(row.total_bytes || row.total_size || row.size_bytes || 0) }}</dd><dt>SHA256</dt><dd>{{ row.sha256 || row.archive_sha256 || '—' }}</dd><dt>入口文件</dt><dd>{{ row.entry_file || 'index.html' }}</dd></dl></template></el-table-column><el-table-column prop="id" label="版本 ID" min-width="130" /><el-table-column label="状态" width="100"><template #default="{row}">{{ row.status === 'ready' ? '可预览' : row.status === 'deleting' ? '清理中' : '不可用' }}</template></el-table-column><el-table-column label="上传时间" min-width="170"><template #default="{row}">{{ dateTime(row.create_time) }}</template></el-table-column><el-table-column label="操作" width="90"><template #default="{row}"><a v-if="canPreview(row)" class="preview-link" :href="previewURL(row)" target="_blank" rel="noopener noreferrer">预览 ↗</a><span v-else class="muted">不可预览</span></template></el-table-column></el-table>
    <div class="action-row" style="margin-top:24px"><el-button v-if="detail.project.status !== 'deleted' && detail.project.moderation_status !== 'blocked'" type="danger" plain @click="beginAction(detail.project, 'block')">下架并锁定</el-button><el-button @click="openAudit(detail.project.id)">查看操作记录</el-button></div>
  </template></el-drawer>
  <AdminConfirm v-model="actionVisible" :title="actionTitles[action]" :description="actionDescriptions[action]" :server-error="actionError" :loading="saving" @confirm="executeAction"><p class="muted">目标：{{ selected?.name || selected?.slug }}（{{ selected?.id }}）</p></AdminConfirm>
</template>
<script>
import AdminConfirm from '@/components/AdminConfirm.vue'
import UserIdentity from '@/components/UserIdentity.vue'
const {accountsApi} = require('@/api/accounts.cjs')
const {dateTime} = require('@/utils/accounts_behavior.cjs')
export default {
  name: 'AdminProjects', components: {AdminConfirm, UserIdentity},
  data() { return {items: [], cursor: '', hasMore: false, loading: false, error: '', filters: {owner_user_id: this.$route.query.owner_user_id || '', query: '', status: '', access_mode: '', moderation_status: ''}, detail: null, detailVisible: false, detailLoading: false, selected: null, action: '', actionVisible: false, actionError: '', saving: false,
    statusText: {draft: '草稿', enabled: '已发布', disabled: '已停用', deleted: '已删除'}, accessText: {owner: '仅本人', members: '指定成员', authenticated: '登录用户', public: '所有人'}, moderationText: {normal: '正常', blocked: '管理员已下架', deleted: '管理员已删除'},
    actionTitles: {block: '下架网页', delete: '删除网页', restore: '恢复网页', unblock: '解除审核锁'}, actionDescriptions: {block: '立即停止普通访问并加审核锁，所有者无法自行发布或恢复。', delete: '立即停止访问，进入删除保留期与文件清理流程，所有者不能自行恢复。', restore: '保留期内恢复为停用状态，不会自动重新发布。已清理的文件无法恢复。', unblock: '解除锁定后保持停用状态，不会自动上线。所有者后续可重新发布。'},
  } },
  created() { this.load(true) },
  methods: {
    dateTime,
    bytes(value) { return value >= 1048576 ? `${(value / 1048576).toFixed(2)} MiB` : `${(value / 1024).toFixed(1)} KiB` },
    canPreview(release) { return release.status === 'ready' && !release.purged_at },
    previewURL(release) { const path = (release.entry_file || 'index.html').split('/').map(encodeURIComponent).join('/'); return `/api/admin/web-share/${encodeURIComponent(this.detail.project.id)}/releases/${encodeURIComponent(release.id)}/preview/${path}` },
    async load(reset) { this.loading = true; this.error = ''; try { const result = await accountsApi.projects({...this.filters, cursor: reset ? '' : this.cursor, limit: 20}); this.items = reset ? result.items : this.items.concat(result.items); this.cursor = result.next_cursor || ''; this.hasMore = !!result.has_more } catch (error) { this.error = error.message } finally { this.loading = false } },
    async viewProject(row) { this.detailVisible = true; this.detailLoading = true; this.detail = null; try { this.detail = await accountsApi.project(row.id) } catch (error) { this.error = error.message; this.detailVisible = false } finally { this.detailLoading = false } },
    beginAction(project, action) { this.selected = project; this.action = action; this.actionVisible = true; this.actionError = '' },
    openAudit(id) { this.detailVisible = false; this.$router.push({path: '/admin/audit-logs', query: {target_type: 'web_project', target_id: id}}) },
    async executeAction(confirmation) { this.saving = true; this.actionError = ''; try { await accountsApi.projectAction(this.selected.id, this.action, this.selected.revision, confirmation); this.actionVisible = false; this.$message.success('网页处置已完成'); if (this.detailVisible) await this.viewProject(this.selected); await this.load(true) } catch (error) { this.actionError = error.status === 409 ? '网页状态已被修改，请关闭弹窗，刷新后重新确认。' : error.message } finally { this.saving = false } },
  },
}
</script>
<style scoped>.moderation-warning{display:block;color:#a35539;margin-top:8px}.release-heading{font-size:18px;margin:32px 0 16px}.release-details{padding:14px}.preview-link{font-size:13px;color:var(--primary-color);text-decoration:none}</style>
