package fileshare

import (
	"context"
	"errors"
	"fmt"
	"io"
	"sort"
	"strconv"

	"github.com/go-sql-driver/mysql"
	"github.com/mcoder2014/home_server/config"
	"github.com/mcoder2014/home_server/domain/dal"
	"github.com/mcoder2014/home_server/domain/model"
	"github.com/mcoder2014/home_server/domain/service/accounts"
	service "github.com/mcoder2014/home_server/domain/service/fileshare"
	"github.com/mcoder2014/home_server/domain/service/passport"
	apperrors "github.com/mcoder2014/home_server/errors"
	"github.com/mcoder2014/home_server/utils"
	"github.com/sirupsen/logrus"
	"gorm.io/gorm"
)

func (application *Application) Upload(ctx context.Context, principal *utils.Principal, originalName string, source io.Reader) (*service.FileView, error) {
	if principal == nil || principal.UserID <= 0 {
		return nil, service.ErrUnauthorized
	}
	conf := config.Global().FileSharing
	release, err := application.AcquireUpload(conf, principal.UserID)
	if err != nil {
		return nil, err
	}
	defer release()
	return application.UploadReserved(ctx, principal, originalName, source, nil)
}

// UploadReserved consumes a slot already acquired by the HTTP boundary. The
// completion callback validates the multipart terminator after StoreUpload has
// consumed the only file part and before any metadata transaction can commit.
func (application *Application) UploadReserved(ctx context.Context, principal *utils.Principal, originalName string, source io.Reader, complete func() error) (*service.FileView, error) {
	if principal == nil || principal.UserID <= 0 {
		return nil, service.ErrUnauthorized
	}
	name, err := service.SafeFilename(originalName)
	if err != nil {
		return nil, err
	}
	conf := config.Global().FileSharing
	database, err := database(ctx)
	if err != nil {
		return nil, err
	}
	if err := checkQuota(database, &conf, principal.UserID, 0); err != nil {
		return nil, err
	}
	fileID := utils.GenInt64ID()
	stored, err := service.StoreUpload(&conf, principal.UserID, fileID, source)
	if err != nil {
		return nil, service.ClassifyStorageError(err)
	}
	if complete != nil {
		if err := complete(); err != nil {
			_ = service.RemoveStoredFile(&conf, stored.StorageKey)
			return nil, err
		}
	}
	file := &model.StoredFile{ID: fileID, OwnerUserID: principal.UserID, OriginalName: name, StorageKey: stored.StorageKey, SizeBytes: stored.SizeBytes, SHA256: stored.SHA256, CreateTime: application.now()}
	unlock := application.lockOwner(principal.UserID)
	defer unlock()
	err = database.Transaction(func(tx *gorm.DB) error {
		if err := requireWritePolicy(ctx, tx, principal, nil); err != nil {
			return err
		}
		if err := checkQuota(tx, &conf, principal.UserID, file.SizeBytes); err != nil {
			return err
		}
		return dal.InsertFile(tx, file)
	})
	if err != nil {
		return resolveUploadCommit(ctx, database, &conf, file, err)
	}
	return fileView(file, 0), nil
}

// resolveUploadCommit removes generated bytes only after proving the row did
// not commit. A database error can include an unknown commit result; in that
// case a failed read deliberately leaves the private bytes in place.
func resolveUploadCommit(ctx context.Context, database *gorm.DB, conf *config.FileSharingConfig, file *model.StoredFile, transactionErr error) (*service.FileView, error) {
	var apiError *apperrors.APIError
	var mysqlError *mysql.MySQLError
	if errors.As(transactionErr, &apiError) || errors.As(transactionErr, &mysqlError) && mysqlError.Number == 1062 {
		_ = service.RemoveStoredFile(conf, file.StorageKey)
		return nil, persistenceError(transactionErr)
	}
	existing, queryErr := dal.FindFile(database.WithContext(ctx), file.ID, false)
	if queryErr != nil {
		return nil, service.ErrDependency
	}
	if existing == nil {
		_ = service.RemoveStoredFile(conf, file.StorageKey)
		return nil, service.ErrDependency
	}
	if existing.StorageKey != file.StorageKey {
		_ = service.RemoveStoredFile(conf, file.StorageKey)
		return nil, service.ErrConflict
	}
	if existing.OwnerUserID != file.OwnerUserID || existing.OriginalName != file.OriginalName || existing.SizeBytes != file.SizeBytes || existing.SHA256 != file.SHA256 || existing.DeletedAt != nil {
		return nil, service.ErrDependency
	}
	return fileView(existing, 0), nil
}

func checkQuota(database *gorm.DB, conf *config.FileSharingConfig, ownerID, addingBytes int64) error {
	count, err := dal.CountOwnedFiles(database, ownerID)
	if err != nil {
		return service.ErrDependency
	}
	bytes, err := dal.SumOwnedFileBytes(database, ownerID)
	if err != nil {
		return service.ErrDependency
	}
	if count >= int64(conf.MaxFilesPerUser) || addingBytes < 0 || addingBytes > conf.MaxUserBytes || bytes > conf.MaxUserBytes-addingBytes {
		return service.ErrRateLimited
	}
	return nil
}

func (application *Application) List(ctx context.Context, ownerID, cursor int64, limit int) (*service.FilePage, error) {
	if ownerID <= 0 || cursor < 0 || limit < 1 || limit > 100 {
		return nil, service.ErrInvalid
	}
	database, err := database(ctx)
	if err != nil {
		return nil, err
	}
	files, err := dal.ListOwnedFiles(database, ownerID, cursor, limit+1)
	if err != nil {
		return nil, service.ErrDependency
	}
	page := &service.FilePage{Items: []*service.FileView{}}
	if len(files) > limit {
		page.HasMore = true
		files = files[:limit]
	}
	ids := make([]int64, 0, len(files))
	for _, file := range files {
		ids = append(ids, file.ID)
	}
	counts, err := dal.CountFileShares(database, ids)
	if err != nil {
		return nil, service.ErrDependency
	}
	for _, file := range files {
		page.Items = append(page.Items, fileView(file, counts[file.ID]))
	}
	if page.HasMore {
		page.NextCursor = strconv.FormatInt(files[len(files)-1].ID, 10)
	}
	return page, nil
}

func (application *Application) Get(ctx context.Context, ownerID, fileID int64) (*service.FileView, error) {
	database, err := database(ctx)
	if err != nil {
		return nil, err
	}
	file, err := dal.FindOwnedFile(database, ownerID, fileID, false, false)
	if err != nil {
		return nil, service.ErrDependency
	}
	if file == nil {
		return nil, service.ErrNotFound
	}
	counts, err := dal.CountFileShares(database, []int64{file.ID})
	if err != nil {
		return nil, service.ErrDependency
	}
	return fileView(file, counts[file.ID]), nil
}

func (application *Application) EligibleUsers(ctx context.Context) ([]service.EligibleUser, error) {
	if accounts.DatabaseMode() {
		users, err := accounts.ListActiveUsers(ctx)
		if err != nil {
			return nil, service.ErrDependency
		}
		result := make([]service.EligibleUser, 0, len(users))
		for _, user := range users {
			display := accounts.DisplayUser(user)
			result = append(result, service.EligibleUser{ID: strconv.FormatInt(user.ID, 10), UserName: display.UserName, DisplayName: display.DisplayName, AvatarURL: display.AvatarURL})
		}
		return result, nil
	}
	users, err := passport.ListUsersWithError(ctx)
	if err != nil {
		return nil, service.ErrDependency
	}
	result := make([]service.EligibleUser, 0, len(users))
	for _, user := range users {
		if user != nil && user.ID > 0 {
			result = append(result, service.EligibleUser{ID: strconv.FormatInt(user.ID, 10), UserName: user.UserName})
		}
	}
	sort.Slice(result, func(i, j int) bool { return result[i].ID < result[j].ID })
	return result, nil
}

func (application *Application) Delete(ctx context.Context, principal *utils.Principal, fileID int64) (map[string]interface{}, error) {
	if principal == nil || principal.UserID <= 0 || fileID <= 0 {
		return nil, service.ErrInvalid
	}
	database, err := database(ctx)
	if err != nil {
		return nil, err
	}
	var key string
	deletedAt := application.now()
	err = database.Transaction(func(tx *gorm.DB) error {
		if err := requireWritePolicy(ctx, tx, principal, nil); err != nil {
			return err
		}
		file, err := dal.FindOwnedFile(tx, principal.UserID, fileID, false, true)
		if err != nil {
			return err
		}
		if file == nil {
			return service.ErrNotFound
		}
		key = file.StorageKey
		updated, err := dal.DeleteOwnedFile(tx, principal.UserID, fileID, deletedAt)
		if err != nil {
			return err
		}
		if !updated {
			return service.ErrConflict
		}
		return nil
	})
	if err != nil {
		return nil, persistenceError(err)
	}
	conf := config.Global().FileSharing
	if err := service.RemoveStoredFile(&conf, key); err != nil {
		logrus.WithField("file_id", fileID).Error("deleted file metadata but could not remove private bytes")
	}
	return map[string]interface{}{"id": strconv.FormatInt(fileID, 10), "deleted_at": deletedAt}, nil
}

func fileView(file *model.StoredFile, shareCount int64) *service.FileView {
	return &service.FileView{ID: strconv.FormatInt(file.ID, 10), Name: file.OriginalName, SizeBytes: file.SizeBytes, SHA256: file.SHA256, ShareCount: shareCount, DeletedAt: file.DeletedAt, CreateTime: file.CreateTime}
}

func fileInvariant(file *model.StoredFile) error {
	if file == nil || file.ID <= 0 || file.OwnerUserID <= 0 || file.SizeBytes < 0 || len(file.SHA256) != 64 || file.StorageKey == "" {
		return fmt.Errorf("invalid stored file metadata")
	}
	return nil
}
